server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: lafine
    password: equipe
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    database: MYSQL
